/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author micha
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textField = new javax.swing.JTextField();
        onRadioButton = new javax.swing.JRadioButton();
        offRadioButton = new javax.swing.JRadioButton();
        consumeButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        buttonNr7 = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        buttonNr9 = new javax.swing.JButton();
        buttonNr8 = new javax.swing.JButton();
        buttonNr4 = new javax.swing.JButton();
        subtractionButton = new javax.swing.JButton();
        buttonNr6 = new javax.swing.JButton();
        buttonNr5 = new javax.swing.JButton();
        buttonNr1 = new javax.swing.JButton();
        additionButton = new javax.swing.JButton();
        buttonNr3 = new javax.swing.JButton();
        buttonNr2 = new javax.swing.JButton();
        commaButton = new javax.swing.JButton();
        scoreButton = new javax.swing.JButton();
        buttonNr0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        textField.setEditable(false);
        textField.setFont(new java.awt.Font("Verdana", 1, 26)); // NOI18N
        textField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(onRadioButton);
        onRadioButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        onRadioButton.setText("ON");
        onRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(offRadioButton);
        offRadioButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        offRadioButton.setText("OFF");
        offRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offRadioButtonActionPerformed(evt);
            }
        });

        consumeButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        consumeButton.setText("C");
        consumeButton.setToolTipText("");
        consumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumeButtonActionPerformed(evt);
            }
        });

        divisionButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        divisionButton.setText("/");
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        deleteButton.setText("<--");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        buttonNr7.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonNr7.setText("7");
        buttonNr7.setToolTipText("");
        buttonNr7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNr7ActionPerformed(evt);
            }
        });

        multiplicationButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        multiplicationButton.setText("*");
        multiplicationButton.setToolTipText("");
        multiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationButtonActionPerformed(evt);
            }
        });

        buttonNr9.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonNr9.setText("9");
        buttonNr9.setToolTipText("");
        buttonNr9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNr9ActionPerformed(evt);
            }
        });

        buttonNr8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonNr8.setText("8");
        buttonNr8.setToolTipText("");
        buttonNr8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNr8ActionPerformed(evt);
            }
        });

        buttonNr4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonNr4.setText("4");
        buttonNr4.setToolTipText("");
        buttonNr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNr4ActionPerformed(evt);
            }
        });

        subtractionButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        subtractionButton.setText("-");
        subtractionButton.setToolTipText("");
        subtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionButtonActionPerformed(evt);
            }
        });

        buttonNr6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonNr6.setText("6");
        buttonNr6.setToolTipText("");
        buttonNr6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNr6ActionPerformed(evt);
            }
        });

        buttonNr5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonNr5.setText("5");
        buttonNr5.setToolTipText("");
        buttonNr5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNr5ActionPerformed(evt);
            }
        });

        buttonNr1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonNr1.setText("1");
        buttonNr1.setToolTipText("");
        buttonNr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNr1ActionPerformed(evt);
            }
        });

        additionButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        additionButton.setText("+");
        additionButton.setToolTipText("");
        additionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionButtonActionPerformed(evt);
            }
        });

        buttonNr3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonNr3.setText("3");
        buttonNr3.setToolTipText("");
        buttonNr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNr3ActionPerformed(evt);
            }
        });

        buttonNr2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonNr2.setText("2");
        buttonNr2.setToolTipText("");
        buttonNr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNr2ActionPerformed(evt);
            }
        });

        commaButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        commaButton.setText(",");
        commaButton.setToolTipText("");
        commaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commaButtonActionPerformed(evt);
            }
        });

        scoreButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        scoreButton.setText("=");
        scoreButton.setToolTipText("");

        buttonNr0.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        buttonNr0.setText("0");
        buttonNr0.setToolTipText("");
        buttonNr0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNr0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(onRadioButton)
                            .addComponent(offRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonNr7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNr8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNr9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonNr4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNr5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNr6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonNr1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNr2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNr3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(commaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNr0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(consumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(onRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(offRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNr9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNr8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNr7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNr6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNr5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNr4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNr3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNr2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNr1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNr0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNr7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNr7ActionPerformed
        textField.setText(textField.getText() + "7");
    }//GEN-LAST:event_buttonNr7ActionPerformed

    private void buttonNr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNr1ActionPerformed
        textField.setText(textField.getText() + "1");
        
    }//GEN-LAST:event_buttonNr1ActionPerformed

    private void buttonNr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNr2ActionPerformed
        textField.setText(textField.getText() + "2");
    }//GEN-LAST:event_buttonNr2ActionPerformed

    private void buttonNr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNr3ActionPerformed
        textField.setText(textField.getText() + "3");
    }//GEN-LAST:event_buttonNr3ActionPerformed

    private void buttonNr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNr4ActionPerformed
        textField.setText(textField.getText() + "4");
    }//GEN-LAST:event_buttonNr4ActionPerformed

    private void buttonNr5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNr5ActionPerformed
        textField.setText(textField.getText() + "5");
    }//GEN-LAST:event_buttonNr5ActionPerformed

    private void buttonNr6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNr6ActionPerformed
        textField.setText(textField.getText() + "6");
    }//GEN-LAST:event_buttonNr6ActionPerformed

    private void buttonNr8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNr8ActionPerformed
        textField.setText(textField.getText() + "8");
    }//GEN-LAST:event_buttonNr8ActionPerformed

    private void buttonNr9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNr9ActionPerformed
        textField.setText(textField.getText() + "9");
    }//GEN-LAST:event_buttonNr9ActionPerformed

    private void buttonNr0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNr0ActionPerformed
        textField.setText(textField.getText() + "0");
    }//GEN-LAST:event_buttonNr0ActionPerformed

    private void additionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionButtonActionPerformed
        textField.setText(textField.getText() + "+");
    }//GEN-LAST:event_additionButtonActionPerformed

    private void subtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionButtonActionPerformed
        textField.setText(textField.getText() + "-");
    }//GEN-LAST:event_subtractionButtonActionPerformed

    private void multiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationButtonActionPerformed
        textField.setText(textField.getText() + "*");
    }//GEN-LAST:event_multiplicationButtonActionPerformed

    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonActionPerformed
        textField.setText(textField.getText() + "/");
    }//GEN-LAST:event_divisionButtonActionPerformed

    private void commaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commaButtonActionPerformed
        textField.setText(textField.getText() + ".");
    }//GEN-LAST:event_commaButtonActionPerformed

    private void offRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offRadioButtonActionPerformed
        enableRadioButton(false);
    }//GEN-LAST:event_offRadioButtonActionPerformed

    private void onRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRadioButtonActionPerformed
        enableRadioButton(true);
    }//GEN-LAST:event_onRadioButtonActionPerformed

    private void consumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumeButtonActionPerformed
        textField.setText("");
    }//GEN-LAST:event_consumeButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if(textField.getText().length()>0)
        {
            int position = textField.getText().length()-1;
            
            StringBuilder text;
            text = new StringBuilder(textField.getText());
            text.deleteCharAt(position);
            textField.setText(text.toString());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed
    //
    public void enableRadioButton(boolean enable)
    {
        textField.setEnabled(enable);

        buttonNr0.setEnabled(enable);
        buttonNr1.setEnabled(enable);
        buttonNr2.setEnabled(enable);
        buttonNr3.setEnabled(enable);
        buttonNr4.setEnabled(enable);
        buttonNr5.setEnabled(enable);
        buttonNr6.setEnabled(enable);
        buttonNr7.setEnabled(enable);
        buttonNr8.setEnabled(enable);
        buttonNr9.setEnabled(enable);
        additionButton.setEnabled(enable);
        subtractionButton.setEnabled(enable);
        multiplicationButton.setEnabled(enable);
        divisionButton.setEnabled(enable);
        commaButton.setEnabled(enable);
        scoreButton.setEnabled(enable);
        consumeButton.setEnabled(enable);
        deleteButton.setEnabled(enable);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonNr0;
    private javax.swing.JButton buttonNr1;
    private javax.swing.JButton buttonNr2;
    private javax.swing.JButton buttonNr3;
    private javax.swing.JButton buttonNr4;
    private javax.swing.JButton buttonNr5;
    private javax.swing.JButton buttonNr6;
    private javax.swing.JButton buttonNr7;
    private javax.swing.JButton buttonNr8;
    private javax.swing.JButton buttonNr9;
    private javax.swing.JButton commaButton;
    private javax.swing.JButton consumeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JRadioButton offRadioButton;
    private javax.swing.JRadioButton onRadioButton;
    private javax.swing.JButton scoreButton;
    private javax.swing.JButton subtractionButton;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
